<?php
$this->iso = array(
  array('id' => '1','iso' => 'RU-AD','region_name' => 'Республика Адыгея'),
  array('id' => '2','iso' => 'RU-BA','region_name' => 'Республика Башкортостан'),
  array('id' => '3','iso' => 'RU-BU','region_name' => 'Республика Бурятия'),
  array('id' => '4','iso' => 'RU-AL','region_name' => 'Республика Алтай'),
  array('id' => '5','iso' => 'RU-DA','region_name' => 'Республика Дагестан'),
  array('id' => '6','iso' => 'RU-IN','region_name' => 'Республика Ингушетия'),
  array('id' => '7','iso' => 'RU-KB','region_name' => 'Кабардино-Балкарская республика'),
  array('id' => '8','iso' => 'RU-KL','region_name' => 'Республика Калмыкия'),
  array('id' => '9','iso' => 'RU-KC','region_name' => 'Карачаево-Черкесская республика'),
  array('id' => '10','iso' => 'RU-KR','region_name' => 'Республика Карелия'),
  array('id' => '11','iso' => 'RU-KO','region_name' => 'Республика Коми'),
  array('id' => '12','iso' => 'RU-ME','region_name' => 'Республика Марий Эл'),
  array('id' => '13','iso' => 'RU-MO','region_name' => 'Республика Мордовия'),
  array('id' => '14','iso' => 'RU-SA','region_name' => 'Республика Саха (Якутия)'),
  array('id' => '15','iso' => 'RU-SE','region_name' => 'Республика Северная Осетия - Алания'),
  array('id' => '16','iso' => 'RU-TA','region_name' => 'Республика Татарстан'),
  array('id' => '17','iso' => 'RU-TY','region_name' => 'Республика Тыва'),
  array('id' => '18','iso' => 'RU-UD','region_name' => 'Удмуртская республика'),
  array('id' => '19','iso' => 'RU-KK','region_name' => 'Республика Хакасия'),
  array('id' => '21','iso' => 'RU-CU','region_name' => 'Чувашская республика'),
  array('id' => '22','iso' => 'RU-ALT','region_name' => 'Алтайский край'),
  array('id' => '23','iso' => 'RU-KDA','region_name' => 'Краснодарский край'),
  array('id' => '24','iso' => 'RU-KYA','region_name' => 'Красноярский край'),
  array('id' => '25','iso' => 'RU-PRI','region_name' => 'Приморский край'),
  array('id' => '26','iso' => 'RU-STA','region_name' => 'Ставропольский край'),
  array('id' => '27','iso' => 'RU-KHA','region_name' => 'Хабаровский край'),
  array('id' => '28','iso' => 'RU-AMU','region_name' => 'Амурская область'),
  array('id' => '29','iso' => 'RU-ARK','region_name' => 'Архангельская область'),
  array('id' => '30','iso' => 'RU-AST','region_name' => 'Астраханская область'),
  array('id' => '31','iso' => 'RU-BEL','region_name' => 'Белгородская область'),
  array('id' => '32','iso' => 'RU-BRY','region_name' => 'Брянская область'),
  array('id' => '33','iso' => 'RU-VLA','region_name' => 'Владимирская область'),
  array('id' => '34','iso' => 'RU-VGG','region_name' => 'Волгоградская область'),
  array('id' => '35','iso' => 'RU-VLG','region_name' => 'Вологодская область'),
  array('id' => '36','iso' => 'RU-VOR','region_name' => 'Воронежская область'),
  array('id' => '37','iso' => 'RU-IVA','region_name' => 'Ивановская область'),
  array('id' => '38','iso' => 'RU-IRK','region_name' => 'Иркутская область'),
  array('id' => '39','iso' => 'RU-KGD','region_name' => 'Калининградская область'),
  array('id' => '40','iso' => 'RU-KLU','region_name' => 'Калужская область'),
  array('id' => '41','iso' => 'RU-KAM','region_name' => 'Камчатский край'),
  array('id' => '42','iso' => 'RU-KEM','region_name' => 'Кемеровская область'),
  array('id' => '43','iso' => 'RU-KIR','region_name' => 'Кировская область'),
  array('id' => '44','iso' => 'RU-KOS','region_name' => 'Костромская область'),
  array('id' => '45','iso' => 'RU-KGN','region_name' => 'Курганская область'),
  array('id' => '46','iso' => 'RU-KRS','region_name' => 'Курская область'),
  array('id' => '47','iso' => 'RU-LEN','region_name' => 'Ленинградская область'),
  array('id' => '48','iso' => 'RU-LIP','region_name' => 'Липецкая область'),
  array('id' => '49','iso' => 'RU-MAG','region_name' => 'Магаданская область'),
  array('id' => '50','iso' => 'RU-MOS','region_name' => 'Московская область'),
  array('id' => '51','iso' => 'RU-MUR','region_name' => 'Мурманская область'),
  array('id' => '52','iso' => 'RU-NIZ','region_name' => 'Нижегородская область'),
  array('id' => '53','iso' => 'RU-NGR','region_name' => 'Новгородская область'),
  array('id' => '54','iso' => 'RU-NVS','region_name' => 'Новосибирская область'),
  array('id' => '55','iso' => 'RU-OMS','region_name' => 'Омская область'),
  array('id' => '56','iso' => 'RU-ORE','region_name' => 'Оренбургская область'),
  array('id' => '57','iso' => 'RU-ORL','region_name' => 'Орловская область'),
  array('id' => '58','iso' => 'RU-PNZ','region_name' => 'Пензенская область'),
  array('id' => '59','iso' => 'RU-PER','region_name' => 'Пермский край'),
  array('id' => '60','iso' => 'RU-PSK','region_name' => 'Псковская область'),
  array('id' => '61','iso' => 'RU-ROS','region_name' => 'Ростовская область'),
  array('id' => '62','iso' => 'RU-RYA','region_name' => 'Рязанская область'),
  array('id' => '63','iso' => 'RU-SAM','region_name' => 'Самарская область'),
  array('id' => '64','iso' => 'RU-SAR','region_name' => 'Саратовская область'),
  array('id' => '65','iso' => 'RU-SAK','region_name' => 'Сахалинская область'),
  array('id' => '66','iso' => 'RU-SVE','region_name' => 'Свердловская область'),
  array('id' => '67','iso' => 'RU-SMO','region_name' => 'Смоленская область'),
  array('id' => '68','iso' => 'RU-TAM','region_name' => 'Тамбовская область'),
  array('id' => '69','iso' => 'RU-TVE','region_name' => 'Тверская область'),
  array('id' => '70','iso' => 'RU-TOM','region_name' => 'Томская область'),
  array('id' => '71','iso' => 'RU-TUL','region_name' => 'Тульская область'),
  array('id' => '72','iso' => 'RU-TYU','region_name' => 'Тюменская область'),
  array('id' => '73','iso' => 'RU-ULY','region_name' => 'Ульяновская область'),
  array('id' => '74','iso' => 'RU-CHE','region_name' => 'Челябинская область'),
  array('id' => '75','iso' => 'RU-ZAB','region_name' => 'Забайкальский край'),
  array('id' => '76','iso' => 'RU-YAR','region_name' => 'Ярославская область'),
  array('id' => '77','iso' => 'RU-MOW','region_name' => 'Москва'),
  array('id' => '78','iso' => 'RU-SPE','region_name' => 'Санкт-Петербург'),
  array('id' => '79','iso' => 'RU-YEV','region_name' => 'Еврейская автономная область'),
  array('id' => '82','iso' => 'RU-CR','region_name' => 'Республика Крым'),
  array('id' => '83','iso' => 'RU-NEN','region_name' => 'Ненецкий автономный округ'),
  array('id' => '86','iso' => 'RU-KHM','region_name' => 'Ханты-Мансийский автономный округ - Югра'),
  array('id' => '87','iso' => 'RU-CHU','region_name' => 'Чукотский автономный округ'),
  array('id' => '89','iso' => 'RU-YAN','region_name' => 'Ямало-Ненецкий автономный округ'),
  array('id' => '92','iso' => 'RU-SEV','region_name' => 'Севастополь'),
  array('id' => '95','iso' => 'RU-CE','region_name' => 'Чеченская республика')
);
